export enum OperateType{
  CREAT=1,UPDATE=2,DELETE=3,RUNIDCASE=4,RUNTMPCASE=5,RUNSCENE=6,COVERT=7,STOPTASK=8,RESTARTTASK=9
}

export enum OperateModule{
  CASE=1,CATALOG=2,ENV=3,ENDPOINT=4,HISTORY=5,OPERATE=6,RUN=7,SENCE=8,TASK=9,TOKEN=10
}
