SET AUTOCOMMIT=0;
START TRANSACTION;
ALTER TABLE "history" ALTER COLUMN "endTime" SET DEFAULT '2020-03-17 08:46:05.091';
ALTER TABLE "history" ALTER COLUMN "startTime" SET DEFAULT '2020-03-17 08:46:05.091';
ALTER TABLE "catalog" ALTER COLUMN "parentId" DROP DEFAULT;
ALTER TABLE "scene" DROP COLUMN "sceneGrade";
DROP TYPE "scene_scenegrade_enum";
COMMIT;