SET AUTOCOMMIT=0;
START TRANSACTION;
ALTER TABLE "history" ALTER COLUMN "endTime" SET DEFAULT '2020-02-27 08:06:55.9';
ALTER TABLE "history" ALTER COLUMN "startTime" SET DEFAULT '2020-02-27 08:06:55.9';
ALTER TABLE "catalog" ALTER COLUMN "parentId" DROP DEFAULT;
ALTER TABLE "catalog" ADD "userId" integer;
ALTER TABLE "catalog" ADD CONSTRAINT "FK_6b0daca4bde404abcf88f305f03" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;