ALTER TABLE "case" DROP CONSTRAINT "FK_7bedaea7848005f61a37b1fe254";
ALTER TABLE "case" DROP COLUMN "jmeterId";
ALTER TABLE "case" ALTER COLUMN "assertText" DROP NOT NULL;
COMMENT ON COLUMN "case"."assertText" IS '断言内容';
ALTER TABLE "case" ADD "isRealDelete" boolean NOT NULL DEFAULT false;
ALTER TYPE "public"."secheduler_status_enum" RENAME TO "secheduler_status_enum_old";
CREATE TYPE "secheduler_status_enum" AS ENUM('1', '2', '3');
ALTER TABLE "secheduler" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "secheduler" ALTER COLUMN "status" TYPE "secheduler_status_enum" USING "status"::"text"::"secheduler_status_enum";
ALTER TABLE "secheduler" ALTER COLUMN "status" SET DEFAULT '2';
DROP TYPE "secheduler_status_enum_old";
ALTER TABLE "jmeter" ADD "isRealDelete" boolean NOT NULL DEFAULT false;